"""
WhatsApp notification module (via Twilio)

Setup:
  1. Create a free Twilio account at https://www.twilio.com
  2. Activate the WhatsApp Sandbox:
       Console → Messaging → Try it out → Send a WhatsApp message
  3. Copy your Account SID and Auth Token from the Twilio Console dashboard
  4. Set TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_WHATSAPP_FROM,
     and WHATSAPP_TO in your .env file

For production (non-sandbox):
  - Apply for a WhatsApp Business number via the Twilio Console
  - Update TWILIO_WHATSAPP_FROM to your approved number
"""
import os
from typing import Optional
from datetime import datetime
from ..logger import setup_logger

logger = setup_logger(__name__)


class WhatsAppNotifier:
    """Send WhatsApp notifications with AI news digest via Twilio."""

    def __init__(
        self,
        account_sid: Optional[str] = None,
        auth_token: Optional[str] = None,
        from_number: Optional[str] = None,
        to_number: Optional[str] = None,
    ):
        """
        Initialize WhatsAppNotifier.

        Args:
            account_sid:  Twilio Account SID (or set TWILIO_ACCOUNT_SID)
            auth_token:   Twilio Auth Token  (or set TWILIO_AUTH_TOKEN)
            from_number:  Twilio WhatsApp sender, e.g. 'whatsapp:+14155238886'
                          (or set TWILIO_WHATSAPP_FROM)
            to_number:    Recipient WhatsApp number, e.g. 'whatsapp:+1234567890'
                          (or set WHATSAPP_TO)
        """
        self.account_sid = account_sid or os.getenv("TWILIO_ACCOUNT_SID", "")
        self.auth_token  = auth_token  or os.getenv("TWILIO_AUTH_TOKEN", "")
        self.from_number = from_number or os.getenv("TWILIO_WHATSAPP_FROM", "")
        self.to_number   = to_number   or os.getenv("WHATSAPP_TO", "")

        if not all([self.account_sid, self.auth_token, self.from_number, self.to_number]):
            logger.warning("WhatsApp (Twilio) credentials not fully configured.")
        else:
            logger.info(f"WhatsAppNotifier initialized (to: {self._mask(self.to_number)})")

    # ── Public API ─────────────────────────────────────────────────────────────

    def send(
        self,
        content: str,
        title: Optional[str] = None,
        language: str = "en",
    ) -> bool:
        """
        Send a plain text WhatsApp message.

        Args:
            content:  Message body
            title:    Optional title prepended to the message
            language: Language code used in the default title

        Returns:
            True if sent successfully, False otherwise
        """
        if not self._configured():
            return False

        if title is None:
            today = datetime.now().strftime("%Y-%m-%d")
            lang_suffix = f" [{language.upper()}]" if language != "en" else ""
            title = f"AI News Digest - {today}{lang_suffix}"

        footer = "\n\n───────────────\n_Generated by AI News Bot_"
        message = f"*{title}*\n\n{content}{footer}"

        return self._send_messages(self._split_message(message))

    def send_digest_summary(
        self,
        digest: dict,
        language: str = "en",
        channel_title: str = "AI News",
    ) -> bool:
        """
        Send a structured digest summary to WhatsApp.

        Mirrors TelegramNotifier.send_digest_summary() using WhatsApp
        text formatting (* for bold, _ for italic).

        Args:
            digest:        Dict produced by Summarizer.summarize()
            language:      Language code for the subject suffix
            channel_title: Title shown in the message header

        Returns:
            True if sent successfully, False otherwise
        """
        if not self._configured():
            logger.error("WhatsApp credentials not configured. Skipping.")
            return False

        date = digest.get("date", "")
        headline = digest.get("headline", "")
        categories = digest.get("categories", [])
        lang_suffix = f" [{language.upper()}]" if language != "en" else ""

        lines = [
            f"📰 *{channel_title} — {date}{lang_suffix}*",
            "",
            f"_{headline}_",
            "",
        ]

        for cat in categories:
            cat_name = cat.get("name", "")
            stories = cat.get("stories", [])
            if not stories:
                continue

            lines.append(f"*{cat_name}*")
            sorted_stories = sorted(
                stories,
                key=lambda s: {"high": 0, "medium": 1, "low": 2}.get(
                    s.get("importance", "medium"), 1
                ),
            )
            for story in sorted_stories[:3]:
                title_text = story.get("title", "")
                url        = story.get("url", "")
                pro        = story.get("pro", "").strip()
                con        = story.get("con", "").strip()

                lines.append(f"• {title_text}")
                if url:
                    lines.append(f"  {url}")
                if pro:
                    lines.append(f"  ✅ {pro}")
                if con:
                    lines.append(f"  ⚠️ {con}")
            lines.append("")

        lines.append("_Generated by AI News Bot_")

        message = "\n".join(lines)
        messages = self._split_message(message)

        success = self._send_messages(messages)
        if success:
            logger.info("WhatsApp digest summary sent successfully.")
        return success

    # ── Internal ───────────────────────────────────────────────────────────────

    def _configured(self) -> bool:
        if not all([self.account_sid, self.auth_token, self.from_number, self.to_number]):
            logger.error("WhatsApp (Twilio) credentials not fully configured.")
            return False
        return True

    def _send_messages(self, messages: list) -> bool:
        try:
            from twilio.rest import Client  # lazy import — only needed at send time
        except ImportError:
            logger.error(
                "twilio package not installed. Run: pip install twilio"
            )
            return False

        try:
            client = Client(self.account_sid, self.auth_token)
            for idx, msg in enumerate(messages):
                client.messages.create(
                    body=msg,
                    from_=self.from_number,
                    to=self.to_number,
                )
                logger.info(f"WhatsApp message {idx + 1}/{len(messages)} sent.")
            return True
        except Exception as exc:
            logger.error(f"Failed to send WhatsApp message: {exc}", exc_info=True)
            return False

    def _split_message(self, message: str, max_length: int = 4096) -> list:
        """Split long messages into chunks that fit WhatsApp's character limit."""
        if len(message) <= max_length:
            return [message]

        chunks = []
        current_chunk: list = []
        current_length = 0

        for line in message.split("\n"):
            line_length = len(line) + 1
            if current_length + line_length > max_length:
                chunks.append("\n".join(current_chunk))
                current_chunk = [line]
                current_length = line_length
            else:
                current_chunk.append(line)
                current_length += line_length

        if current_chunk:
            chunks.append("\n".join(current_chunk))

        return chunks

    def _mask(self, number: str) -> str:
        """Mask a phone number for logging."""
        if len(number) <= 6:
            return "***"
        return f"{number[:6]}***{number[-2:]}"
